CREATE DATABASE IF NOT EXISTS u0794050_crm
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE u0794050_crm;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  login VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  city VARCHAR(128) NULL,
  district VARCHAR(128) NULL,
  transport_mode VARCHAR(128) NULL,
  contacts TEXT NULL,
  registered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_activity DATETIME NULL,
  working_days JSON NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;
